version: "2"

services:
  app:
    image: faffousa/pfe:courzeloapp
    container_name: courzeloapp
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - .m2:/root/.m2

volumes:
  db:
